version: '3'

services:
  app:
    build:
      context: .      
    container_name: my_nest_app
    restart: always
    ports:
      - '4000:3000'
    environment:
      - DATABASE_URL=postgresql://admin:admin@my_postgres_db:5432/mydb
      - CRYPT_SALT=10
      - JWT_SECRET_KEY=secret123123
      - JWT_SECRET_REFRESH_KEY=secret123123
      - TOKEN_EXPIRE_TIME=1h
      - TOKEN_REFRESH_EXPIRE_TIME=24h
    depends_on:
      - db
    networks:
      - my_network

  db:
    image: postgres:latest
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge
