version: '3'

services:
  app:
    build:
      context: .
    container_name: my_nest_app
    restart: always
    ports:
      - '4000:3000'
    environment:
      DATABASE_URL: ${POSTGRES_DB}
    depends_on:
      - db
    networks:
      - my_network

  db:
    image: postgres:latest
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge
