version: '3'

services:
  localhost:
    build:
      context: .
      target: development
      args:
        - DATABASE_URL=${DATABASE_URL}
    container_name: my_nest_app
    restart: always
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - '${PORT}:${PORT}'
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my_network

  db:
    image: postgres
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network
    expose:
      - ${DB_PORT}
    healthcheck:
      test: ['CMD-SHELL', '${HEALTHCHECK_TEST_CMD}']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}
          gateway: ${GATEWAY}
          ip_range: ${IP_RANGE}    
